/**
 * 最新防災グッズを取得する処理
 * 
 */
public without sharing class LatestDisasterGear {

    // @InvocableMethod
    // public static List<Response> getLatestDisasterProduct() {

    //     List<Session__c> sessions =
    //         ExperienceSessionController.getSessions(contact);

    //     // Create expected response
    //     List<Response> responses = new List<Response>();
    //     Response res = new Response();
    //     res.prompt = JSON.serialize(sessions);
    //     responses.add(res);
    //     return responses;
    // }

    // // The variables in this class need to match the prompt template inputs,
    // // that may be different on each prompt template
    // public class Request {
    //     @InvocableVariable(required=true)
    //     public Contact myContact;
    // }

    // public class Response {
    //     @InvocableVariable
    //     public String Prompt;
    // }

}